name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        # Install the package and all dependencies
        uv pip install -e ".[dev]"
        # Ensure pytest-asyncio is installed
        uv pip install pytest-asyncio
    
    - name: Lint with ruff
      run: |
        ruff check .
    
    - name: Run tests
      run: |
        python -m pytest -v
      env:
        # Provide mock API keys for testing
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'sk-mock-key' }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY || 'sk-ant-mock-key' }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY || 'mock-key' }}
        # Default to using Gemini for tests since it's what the tests expect
        DEFAULT_LLM_PROVIDER: "gemini"
        DEFAULT_LLM_MODEL: "gemini-2.0-flash" 