name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety tomli
    
    - name: Run safety check
      run: |
        # Extract dependencies from pyproject.toml to requirements.txt format
        python -c "import tomli; print('\n'.join([dep.split('>=')[0] for dep in tomli.loads(open('pyproject.toml', 'rb').read())['project']['dependencies']]))" > requirements.txt
        safety check -r requirements.txt 